name: Sync upstream

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.WORKFLOW_SYNC_PAT }}

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: xbapps/xbvr
          upstream_sync_branch: master
          target_sync_branch: master
          upstream_pull_args: --ff-only
          target_repo_token: ${{ secrets.WORKFLOW_SYNC_PAT }}
